from bridges.python.src.sdk.leon import leon
from bridges.python.src.sdk.types import ActionParams

import os
from docx import Document


def run(params: ActionParams) -> None:
    """Generate a simple report"""
    output = os.path.join(os.getcwd(), 'report.docx')
    try:
        doc = Document()
        doc.add_heading('Report', 0)
        doc.add_paragraph('This is an autogenerated report.')
        doc.save(output)
        leon.answer({'key': 'done'})
    except Exception:
        leon.answer({'key': 'error'})
